from NDIlib.NDIlib import AudioFrameInterleaved16s
from NDIlib.NDIlib import AudioFrameInterleaved32f
from NDIlib.NDIlib import AudioFrameInterleaved32s
from NDIlib.NDIlib import AudioFrameV2
from NDIlib.NDIlib import AudioFrameV3
from NDIlib.NDIlib import FindCreate
from NDIlib.NDIlib import FindInstance
from NDIlib.NDIlib import FourCCAudioType
from NDIlib.NDIlib import FourCCVideoType
from NDIlib.NDIlib import FrameFormatType
from NDIlib.NDIlib import FrameSyncInstance
from NDIlib.NDIlib import FrameType
from NDIlib.NDIlib import MetadataFrame
from NDIlib.NDIlib import RecvBandwidth
from NDIlib.NDIlib import RecvColorFormat
from NDIlib.NDIlib import RecvCreateV3
from NDIlib.NDIlib import RecvInstance
from NDIlib.NDIlib import RecvPerformance
from NDIlib.NDIlib import RecvQueue
from NDIlib.NDIlib import RecvRecordingTime
from NDIlib.NDIlib import RoutingCreate
from NDIlib.NDIlib import RoutingInstance
from NDIlib.NDIlib import SendCreate
from NDIlib.NDIlib import SendInstance
from NDIlib.NDIlib import Source
from NDIlib.NDIlib import Tally
from NDIlib.NDIlib import VideoFrameV2
from NDIlib.NDIlib import destroy
from NDIlib.NDIlib import find_create_v2
from NDIlib.NDIlib import find_destroy
from NDIlib.NDIlib import find_get_current_sources
from NDIlib.NDIlib import find_wait_for_sources
from NDIlib.NDIlib import framesync_audio_queue_depth
from NDIlib.NDIlib import framesync_capture_audio
from NDIlib.NDIlib import framesync_capture_audio_v2
from NDIlib.NDIlib import framesync_capture_video
from NDIlib.NDIlib import framesync_create
from NDIlib.NDIlib import framesync_destroy
from NDIlib.NDIlib import framesync_free_audio
from NDIlib.NDIlib import framesync_free_audio_v2
from NDIlib.NDIlib import framesync_free_video
from NDIlib.NDIlib import initialize
from NDIlib.NDIlib import is_supported_CPU
from NDIlib.NDIlib import recv_add_connection_metadata
from NDIlib.NDIlib import recv_capture_v2
from NDIlib.NDIlib import recv_capture_v3
from NDIlib.NDIlib import recv_clear_connection_metadata
from NDIlib.NDIlib import recv_connect
from NDIlib.NDIlib import recv_create_v3
from NDIlib.NDIlib import recv_destroy
from NDIlib.NDIlib import recv_free_audio_v2
from NDIlib.NDIlib import recv_free_audio_v3
from NDIlib.NDIlib import recv_free_metadata
from NDIlib.NDIlib import recv_free_string
from NDIlib.NDIlib import recv_free_video_v2
from NDIlib.NDIlib import recv_get_no_connections
from NDIlib.NDIlib import recv_get_performance
from NDIlib.NDIlib import recv_get_queue
from NDIlib.NDIlib import recv_get_web_control
from NDIlib.NDIlib import recv_ptz_auto_focus
from NDIlib.NDIlib import recv_ptz_exposure_auto
from NDIlib.NDIlib import recv_ptz_exposure_manual
from NDIlib.NDIlib import recv_ptz_exposure_manual_v2
from NDIlib.NDIlib import recv_ptz_focus
from NDIlib.NDIlib import recv_ptz_focus_speed
from NDIlib.NDIlib import recv_ptz_is_supported
from NDIlib.NDIlib import recv_ptz_pan_tilt
from NDIlib.NDIlib import recv_ptz_pan_tilt_speed
from NDIlib.NDIlib import recv_ptz_recall_preset
from NDIlib.NDIlib import recv_ptz_store_preset
from NDIlib.NDIlib import recv_ptz_white_balance_auto
from NDIlib.NDIlib import recv_ptz_white_balance_indoor
from NDIlib.NDIlib import recv_ptz_white_balance_manual
from NDIlib.NDIlib import recv_ptz_white_balance_oneshot
from NDIlib.NDIlib import recv_ptz_white_balance_outdoor
from NDIlib.NDIlib import recv_ptz_zoom
from NDIlib.NDIlib import recv_ptz_zoom_speed
from NDIlib.NDIlib import recv_recording_get_error
from NDIlib.NDIlib import recv_recording_get_filename
from NDIlib.NDIlib import recv_recording_get_times
from NDIlib.NDIlib import recv_recording_is_recording
from NDIlib.NDIlib import recv_recording_is_supported
from NDIlib.NDIlib import recv_recording_set_audio_level
from NDIlib.NDIlib import recv_recording_start
from NDIlib.NDIlib import recv_recording_stop
from NDIlib.NDIlib import recv_send_metadata
from NDIlib.NDIlib import recv_set_tally
from NDIlib.NDIlib import routing_change
from NDIlib.NDIlib import routing_clear
from NDIlib.NDIlib import routing_create
from NDIlib.NDIlib import routing_destroy
from NDIlib.NDIlib import routing_get_no_connections
from NDIlib.NDIlib import send_add_connection_metadata
from NDIlib.NDIlib import send_capture
from NDIlib.NDIlib import send_clear_connection_metadata
from NDIlib.NDIlib import send_create
from NDIlib.NDIlib import send_destroy
from NDIlib.NDIlib import send_free_metadata
from NDIlib.NDIlib import send_get_no_connections
from NDIlib.NDIlib import send_get_source_name
from NDIlib.NDIlib import send_get_tally
from NDIlib.NDIlib import send_send_audio_v2
from NDIlib.NDIlib import send_send_audio_v3
from NDIlib.NDIlib import send_send_metadata
from NDIlib.NDIlib import send_send_video_async_v2
from NDIlib.NDIlib import send_send_video_v2
from NDIlib.NDIlib import send_set_failover
from NDIlib.NDIlib import util_P216_to_V210
from NDIlib.NDIlib import util_V210_to_P216
from NDIlib.NDIlib import util_audio_from_interleaved_16s_v2
from NDIlib.NDIlib import util_audio_from_interleaved_32f_v2
from NDIlib.NDIlib import util_audio_from_interleaved_32s_v2
from NDIlib.NDIlib import util_audio_to_interleaved_16s_v2
from NDIlib.NDIlib import util_audio_to_interleaved_32f_v2
from NDIlib.NDIlib import util_audio_to_interleaved_32s_v2
from NDIlib.NDIlib import util_send_send_audio_interleaved_16s
from NDIlib.NDIlib import util_send_send_audio_interleaved_32f
from NDIlib.NDIlib import util_send_send_audio_interleaved_32s
from NDIlib.NDIlib import version
from __future__ import annotations
import os as os
import sys as sys
from . import NDIlib
__all__ = ['AudioFrameInterleaved16s', 'AudioFrameInterleaved32f', 'AudioFrameInterleaved32s', 'AudioFrameV2', 'AudioFrameV3', 'FindCreate', 'FindInstance', 'FourCCAudioType', 'FourCCVideoType', 'FrameFormatType', 'FrameSyncInstance', 'FrameType', 'MetadataFrame', 'NDIlib', 'RECV_TIMESTAMP_UNDEFINED', 'RecvBandwidth', 'RecvColorFormat', 'RecvCreateV3', 'RecvInstance', 'RecvPerformance', 'RecvQueue', 'RecvRecordingTime', 'RoutingCreate', 'RoutingInstance', 'SEND_TIMECODE_SYNTHESIZE', 'SendCreate', 'SendInstance', 'Source', 'Tally', 'VideoFrameV2', 'destroy', 'find_create_v2', 'find_destroy', 'find_get_current_sources', 'find_wait_for_sources', 'framesync_audio_queue_depth', 'framesync_capture_audio', 'framesync_capture_audio_v2', 'framesync_capture_video', 'framesync_create', 'framesync_destroy', 'framesync_free_audio', 'framesync_free_audio_v2', 'framesync_free_video', 'initialize', 'is_supported_CPU', 'os', 'recv_add_connection_metadata', 'recv_capture_v2', 'recv_capture_v3', 'recv_clear_connection_metadata', 'recv_connect', 'recv_create_v3', 'recv_destroy', 'recv_free_audio_v2', 'recv_free_audio_v3', 'recv_free_metadata', 'recv_free_string', 'recv_free_video_v2', 'recv_get_no_connections', 'recv_get_performance', 'recv_get_queue', 'recv_get_web_control', 'recv_ptz_auto_focus', 'recv_ptz_exposure_auto', 'recv_ptz_exposure_manual', 'recv_ptz_exposure_manual_v2', 'recv_ptz_focus', 'recv_ptz_focus_speed', 'recv_ptz_is_supported', 'recv_ptz_pan_tilt', 'recv_ptz_pan_tilt_speed', 'recv_ptz_recall_preset', 'recv_ptz_store_preset', 'recv_ptz_white_balance_auto', 'recv_ptz_white_balance_indoor', 'recv_ptz_white_balance_manual', 'recv_ptz_white_balance_oneshot', 'recv_ptz_white_balance_outdoor', 'recv_ptz_zoom', 'recv_ptz_zoom_speed', 'recv_recording_get_error', 'recv_recording_get_filename', 'recv_recording_get_times', 'recv_recording_is_recording', 'recv_recording_is_supported', 'recv_recording_set_audio_level', 'recv_recording_start', 'recv_recording_stop', 'recv_send_metadata', 'recv_set_tally', 'routing_change', 'routing_clear', 'routing_create', 'routing_destroy', 'routing_get_no_connections', 'send_add_connection_metadata', 'send_capture', 'send_clear_connection_metadata', 'send_create', 'send_destroy', 'send_free_metadata', 'send_get_no_connections', 'send_get_source_name', 'send_get_tally', 'send_send_audio_v2', 'send_send_audio_v3', 'send_send_metadata', 'send_send_video_async_v2', 'send_send_video_v2', 'send_set_failover', 'sys', 'util_P216_to_V210', 'util_V210_to_P216', 'util_audio_from_interleaved_16s_v2', 'util_audio_from_interleaved_32f_v2', 'util_audio_from_interleaved_32s_v2', 'util_audio_to_interleaved_16s_v2', 'util_audio_to_interleaved_32f_v2', 'util_audio_to_interleaved_32s_v2', 'util_send_send_audio_interleaved_16s', 'util_send_send_audio_interleaved_32f', 'util_send_send_audio_interleaved_32s', 'version']
RECV_TIMESTAMP_UNDEFINED: int = 9223372036854775807
SEND_TIMECODE_SYNTHESIZE: int = 9223372036854775807
